version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  tests:
    image: mcr.microsoft.com/playwright:v1.43.1-focal
    container_name: automation-tests
    working_dir: /tests
    volumes:
      - ./tests:/tests
    command: >
      bash -c "
        npm install &&
        npx playwright install &&
        npm run test:api &&
        npm run test:contracts &&
        npx playwright test
      "
    depends_on:
      frontend:
        condition: service_healthy
    networks:
      - test-network

networks:
  test-network:
    driver: bridge