# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of Node.js
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: Node.js CI

on:
  push:
    branches: [ "master", "final_project" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_FOLDER: ./final_project
      HEADLESS: true

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: final_project/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('final_project/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ${{ env.BUILD_FOLDER }}

      - name: Run Playwright tests
        run: npm run test
        working-directory: ${{ env.BUILD_FOLDER }}
        
      - name: Debug List contents of build folder
        run: ls -la ${{ env.BUILD_FOLDER }}
